local db = TUNING.MOD_LOL_WP
local keymap = require('core_lol_wp/utils/keymap')

local modid = 'lol_wp'

---@class lang_lol_wp_pedia
local data = {
    lol_wp_pedia_group = { -- All groups
        warrior = 'Warrior Equipment',
        tank = 'Tank Equipment',
        mage = 'Mage Equipment',
        support = 'Support Equipment',
    },
    lol_wp_pedia_group_label = { -- Labels for all items on the left sidebar
        lol_wp_s7_cull = 'Cull',
        lol_wp_s7_obsidianblade = 'Obsidian Blade',
        lol_wp_s7_doranblade = 'Doran Blade',
        lol_wp_s7_doranshield = 'Doran Shield',
        lol_wp_s7_doranring = 'Doran Ring',
        lol_wp_s7_tearsofgoddess = 'Tear of the Goddess',
        gallop_breaker = 'Breaker',
        gallop_whip = 'Iron Whip',
        gallop_bloodaxe = 'Bloodthirster',
        lol_heartsteel = 'Heartsteel',
        gallop_tiamat = 'Tiamat',
        gallop_hydra = 'Hydra',
        riftmaker_weapon = 'Riftmaker',
        nashor_tooth = "Nashor's Tooth",
        crystal_scepter = "Rylai's Crystal Scepter",
        gallop_blackcutter = 'Blackcutter',
        gallop_brokenking = 'Broken King',
        gallop_ad_destroyer = 'AD Destroyer',
        lol_wp_trinity = 'Trinity Force',
        lol_wp_sheen = 'Sheen',
        lol_wp_divine = 'Divine Sunderer',
        lol_wp_overlordbloodarmor = 'Overlord\'s Bloodmail',
        lol_wp_demonicembracehat = 'Demonic Embrace',
        lol_wp_warmogarmor = "Warmog's Armor",
        lol_wp_s8_deathcap = "Rabadon's Deathcap",
        lol_wp_s8_uselessbat = 'Needlessly Large Rod',
        lol_wp_s8_lichbane = "Lich Bane",
        lol_wp_s9_guider = 'Trailblazer',
        lol_wp_s9_eyestone_low = 'Guardian Eye Stone',
        lol_wp_s9_eyestone_high = 'Alert Eye Stone',
        lol_wp_s10_guinsoo = "Guinsoo's Rageblade",
        lol_wp_s10_blastingwand = 'Blasting Wand',
        lol_wp_s10_sunfireaegis = 'Sunfire Aegis',
        lol_wp_s11_amplifyingtome = 'Amplifying Tome',
        lol_wp_s11_darkseal = 'Dark Seal',
        lol_wp_s11_mejaisoulstealer = "Meja's Soulstealer",
        lol_wp_s12_eclipse = 'Eclipse',
        lol_wp_s12_malignance = 'Malignance',
        alchemy_chainsaw = 'Alchemy Chainsaw',
        lol_wp_s13_infinity_edge = 'Infinity Edge',
        lol_wp_s13_statikk_shiv = 'Statikk Shiv',
        lol_wp_s13_statikk_shiv_charged = 'Statikk Shiv (Charged)',
        lol_wp_s13_collector = 'Collector',
        lol_wp_s14_bramble_vest = 'Bramble Vest',
        lol_wp_s14_thornmail = 'Thornmail',
        lol_wp_s14_hubris = 'Hubris',
        lol_wp_s15_crown_of_the_shattered_queen = 'Crown of the Shattered Queen',
        lol_wp_s15_stopwatch = 'Stopwatch',
        lol_wp_s15_zhonya = 'Zhonya\'s Hourglass',
        lol_wp_s16_potion_hp = 'Health Potion',
        lol_wp_s16_potion_compound = 'Refillable Potion',
        lol_wp_s16_potion_corruption = 'Corruption Potion',
        lol_wp_s17_luden = 'Luden\'s Echo',
        lol_wp_s17_liandry = 'Liandry\'s Torment',
        lol_wp_s17_lostchapter = 'Lost Chapter',
        lol_wp_s18_bloodthirster = 'Bloodthirster',
        lol_wp_s18_stormrazor = 'Stormrazor',
        lol_wp_s18_krakenslayer = 'Krakenslayer',
        lol_wp_s19_archangelstaff = 'Archangel\'s Staff',
        lol_wp_s19_archangelstaff_upgrade = 'Seraph\'s Embrace',
        lol_wp_s19_muramana = 'Manamune',
        lol_wp_s19_muramana_upgrade = 'Muramana',
        lol_wp_s19_fimbulwinter_armor = 'Winter\'s Approach',
        lol_wp_s19_fimbulwinter_armor_upgrade = 'Fimbulwinter',
    },
    pedia_items = { -- Pedia items
        lol_wp_s7_cull = {
            name = 'Cull',
            info_instead = '- Type: Weapon/Tool/Scythe\n- Damage: '..db.CULL.DMG..'\n- Health Regeneration: '..db.CULL.ATK_REGEN..'\n- Active: [Harvest]\n\tRight-click to harvest crops in a range like a Shadow Harvester, can be used on enemies, causing area damage equal to the weapon value, with '..db.CULL.SKILL_SWEEP.CD..' seconds cooldown after each harvest.\n- Passive: [Plunder]\n\tKilling a unit will drop '..db.CULL.SKILL_LOOT.GOLD_PERUNIT..' gold blocks, accumulating '..db.CULL.SKILL_LOOT.FINISHED..' kills will explode, dropping '..db.CULL.SKILL_LOOT.GOLD_WHEN_FINISHED..' gold blocks.\n- Durability: None',
        },
        lol_wp_s7_obsidianblade = {
            name = 'Obsidian Blade',
            info_instead = '- Type: Weapon/Dagger\n- Damage: '..db.OBSIDIANBLADE.DMG..'\n- Passive: [Hunter]\n\tAttacking neutral creatures deals double damage and provides '..db.OBSIDIANBLADE.DRAIN..' health drain.\n- Passive: [Hunter]\n\tKilling creatures increases the probability of the most common drop by one and increases the probability of all drops by '..(db.OBSIDIANBLADE.SKILL_HUNTER.CHANCE_UP*100)..'%.\n- Durability: '..db.OBSIDIANBLADE.FINITEUSE..', will break when durability runs out'
        },
        lol_wp_s7_doranblade = {
            name = 'Doran Blade',
            info_instead = '- Type: Weapon/Sword\n- Damage: '..db.DORANBLADE.DMG..' \n- Health Drain: '..db.DORANBLADE.DRAIN..'\n- Durability: '..db.DORANBLADE.FINITEUSE..', will break when durability runs out'
        },
        lol_wp_s7_doranshield = {
            name = 'Doran Shield',
            info_instead = '- Type: Weapon/Shield\n- Damage: '..db.DORANSHIELD.DMG..'\n- Defense: '..(db.DORANSHIELD.ABSORB*100)..'%\n- Active: [Block]\n\tRight-click and select a direction to block attacks from that direction for 1 second, blocking does not consume durability, successful block will additionally restore '..db.DORANSHIELD.SKILL_BLOCK.REGEN_WHEN_SUCCESS..' health.\n- Passive: [Resilience]\n\tRestores '..db.DORANSHIELD.SKILL_RESTORE.REGEN..' health every '..db.DORANSHIELD.SKILL_RESTORE.INTERVAL..' seconds when held.\n- Durability: '..db.DORANSHIELD.FINITEUSE..', will break when durability runs out'
        },
        lol_wp_s7_doranring = {
            name = 'Doran Ring',
            info_instead = '- Type: Accessory/Ring\n- Additional Planar Damage: '..db.DORANRING.PLANAR_DMG_WHEN_EQUIP..'\n- Passive: [Absorption]\n\tIncreases '..db.DORANRING.DAPPERNESS..' san/min when equipped.\n- Durability: None'
        },
        lol_wp_s7_tearsofgoddess = {
            name = 'Tear of the Goddess',
            info_instead = '- Type: Accessory/Magic Stone\n- San Regeneration: '..db.TEARSOFGODDESS.DAPPERNESS..'\n- Can also provide san regeneration when placed in the inventory, stacking effects from multiple items.\n- Passive: [Spellflow]\n\tAttacking once adds '..db.TEARSOFGODDESS.SKILL_SPELLFLOW.NUM_PER_HIT..' layers of passive, each layer increases san limit by '..db.TEARSOFGODDESS.SKILL_SPELLFLOW.SAN_LIMIT_PER_NUM..' san, up to '..db.TEARSOFGODDESS.SKILL_SPELLFLOW.SAN_LIMIT_MAX..' layers, stacking passive has '..db.TEARSOFGODDESS.SKILL_SPELLFLOW.CD..' seconds cooldown.\n- Durability: None\n- Displays the number of stacked layers below the item.'
        },
        gallop_breaker = {name = 'Breaker', info_instead = '- Type: Weapon/Tool/Hammer\n- Damage: 40\n- Movement Speed +5%\n- Work Efficiency: Axes/Hoes/Hammers/Picks/Shovels 300%/Hammer Power 1000%\n- Can mine advanced materials.\n- Passive: [Captain]\n\t5th basic attack deals 140% true damage.\n- Passive: [Blast]\n\t25% chance to instantly kill when mining or chopping.\n- Passive: [Boarding Squad]\n\tHolding Breaker, self and nearby hired units gain 80% armor, work efficiency is doubled, but this effect is disabled if other players are within 5 yards.\n- Holding Breaker will play a ship-breaking song, right-clicking the weapon can switch forms, turn off bgm, all tool functions and above passives are disabled, gaining a special skill:\n- Active: [Deep Sea Impact]\n\tRight-click to create a huge water column, dealing 100 area damage, the indicator is divided into two circles, the inner circle will destroy rocks and trees, will not destroy plants and buildings, the outer circle only deals damage, and the damage is only 50, causing double damage on water. The water column can immediately extinguish flames in the range and water nearby fields, increasing the moisture of the hit targets by 100 points, each release consumes 5 san, cooldown 5 seconds.\n- Passive: [Captain]\n\t5th basic attack deals 140% true damage.\n- Durability: None',''},
        gallop_whip = {name = 'Iron Whip', info_instead = '- Type: Weapon/Chain Hammer\n- Damage: 51\n- Attack Range: 1.5\n- Passive: [Crescent]\n\tAll attacks deal area damage.\n- Durability: 150, will break when durability runs out\n- Repair Material: Flint 20%',''},
        gallop_bloodaxe = {name = 'Bloodthirster', info_instead = '- Type: Weapon/Chain Hammer\n- Damage: 85\n- Attack Range: 2\n- Omnivamp: '..TUNING[string.upper('CONFIG_'..modid..'bloodaxe_health')]..'\n- Each hit on an enemy unit restores 1 health point, stacking up to 10.\n- Active: [Thirsty Strike]\n\tReleases a circular blade wave centered on yourself, dealing 80 area damage, affected by attack multiplier, each hit restores 5 health, no limit, cooldown 5 seconds.\n- Passive: [Crescent]\n\tAll attacks deal area damage.\n- Passive: [Dark Shackles]\n\tEach attack has a 10% chance to release a 4-yard circular shadow cage in the area, affecting all creatures, trapping them for 12 seconds unable to move. Boss creatures are only trapped for 6 seconds, cooldown 10 seconds\n- Holding it will play a Demon Sword song, right-clicking the weapon can turn off.\n- Belongs to the Shadow category, Shadow Level 4, deals 10% more damage to the Moon faction.\n- Durability: 200, will not break when durability runs out\n- Repair Material: Nightmare Fuel 20%/Pure Terror 100%',''},
        lol_heartsteel = {name = 'Heartsteel', info_instead = '- Type: Accessory/Magic Stone\n- Gradually restores health when equipped, restoring 1% of max health every 10 seconds. \n- Active: [Monstrous Devouring]\n\tWithin 5 yards of a boss creature, can charge for 3 seconds, causing an empowered attack, the charged attack deals an additional 60 physical damage (+10% from your health) and grants you 10 permanent max health. Each unit has a 120 seconds cooldown, can stack up to '..( TUNING[string.upper('CONFIG_'..modid..'limit_lol_heartsteel_new')] and (TUNING[string.upper('CONFIG_'..modid..'limit_lol_heartsteel_new')]*10) or 'no limit' )..' points of additional health, can be set to infinite in mod settings, stacking to the limit can also trigger a charged attack, but will not increase the stack. \n- Passive: [Goliath Giant]\n\tEach 100 points of additional health increases your size by 10%, up to 40%, movement speed also increases, health and size will return to normal when the equipment is removed.\n- Defeating Enraged Claus 100% drops blueprint.\n- Durability: None\n- Displays the number of stacked layers below the item.',''},
        gallop_tiamat = {name = 'Tiamat', info_instead = '- Type: Weapon/Tool/Axe/Pickaxe\n- Damage: 45\n- Work Efficiency: Axes/Pickaxes 125%\n- Can mine advanced materials.\n- Active: [Steel Slash]\n\tRight-click to slash at a designated position, consumes 5 durability, deals area damage equal to the weapon value, cooldown 2 seconds.\n- Durability: 800, will break when durability runs out\n- Repair Material: Gold Block 20%',''},
        gallop_hydra = {name = 'Hydra', info_instead = '- Type: Weapon/Spear\n- Damage: 24\n- Attack Range: 2.0\n- Active: [Steel Slash]\n\tRight-click to slash at a designated position, deals area damage equal to the weapon value, cooldown 0.5 seconds.\n- Active: [Overhead Slash]\n\tConverts max health to attack power, normal attacks deal an additional 10% of your max health as physical damage, the higher your health cap, the higher the damage.\n- Defeating Ant Lion 100% drops blueprint.\n- Durability: None',''},
        riftmaker_weapon = {name = 'Riftmaker', info_instead = '- Type: Weapon/Wand/Accessory\n- Planar Damage: 50\n- Attack Range: 5\n- Omnivamp: 7\n- Each attack consumes 2 san.\n- Emits a purple light with a radius of 2.\n- Active: [Void Rift]\n\tUses the effect of a teleportation wand, consumes 50 san and 10% durability.\n- Passive: [Void Corruption]\n\tEach attack deals an additional 25% true damage based on the damage dealt, ignoring enemy armor and damage reduction.\n- Right-clicking the item can convert it to an accessory item:\n- Additional Planar Damage: 20\n- Omnivamp: 3\n- Each attack consumes 2 san.\n- Emits a purple light with a radius of 2.\n- Passive: [Void Corruption]\n\tEach attack deals an additional 10% true damage based on the damage dealt, ignoring enemy armor and damage reduction.\n- Belongs to the Shadow category, Shadow Level 4, consumes -5 san/min when held or equipped, deals 10% more damage to the Moon faction.\n- Durability: 200, will not break when durability runs out\n- Consumes the user\'s sanity to slowly restore durability when equipped, -20 san/min.\n- Repair Material: Nightmare Fuel 20%/Pure Terror 100%',''},
        nashor_tooth = {name = "Nashor's Tooth", info_instead = '- Type: Weapon/Dagger\n- Damage: 5\n- Planar Damage: 51\n- Movement Speed +10%\n- Active: [Avarox\'s Bite]\n\tStabs in a specified direction, dealing 70 planar damage to enemies on the path, cooldown 5 seconds.\n- Passive: [Void Erosion]\n\tEach attack increases planar damage by 1 point, up to 25 points planar damage, lasting 10 seconds, stacking resets after 10 seconds of no attacks.\n- Belongs to the Shadow category, Shadow Level 2, consumes -10 san/min when held, deals 10% more damage to the Moon faction.\n- Defeating Giant Cave Worm 100% drops a finished product.\n- Durability: 200, will not break when durability runs out\n- Repair Material: Nightmare Fuel 20%, Pure Terror 100%',''},
        crystal_scepter = {name = "Rylai's Crystal Scepter", info_instead = '- Type: Weapon/Wand\n- Planar Damage: 40\n- Attack Range: 8\n- Movement Speed +20%\n- Active: [Ice Tomb]\n\tSummons Claus\'s ice array, freezing all enemies in range, consumes 20 san, cooldown 20 seconds.\n- Passive: [Frostbite]\n\tEach attack deals 30% slow and 0.5 layer of freeze, lasting 1 second.\n- Defeating Monoceros 100% drops blueprint.\n- Defeating Crystal Monoceros 75% drops a finished product.\n- Durability: None',''},
        gallop_blackcutter = {name = 'Blackcutter', info_instead = '- Type: Weapon/Tool/Axe\n- Damage: 68\n- Attack Range: 1.2\n- Movement Speed -10%\n- Work Efficiency: Axes 300%\n- Active: [Noxus Guillotine]\n\tRight-click enemy to release a jump strike, dealing 136 true damage, ignoring enemy armor and damage reduction, each bleed stack doubles the current damage, up to 136x5=680 true damage, affected by attack multiplier, using it refreshes cooldown if the enemy is killed, and puts nearby enemies into fear for 4 seconds.\n- Passive [Cutting]\n\tEach attack applies a bleed effect, dealing 5 true damage per second, also increases movement speed by 20%, lasting 5 seconds, attacking again within 5 seconds stacks the bleed effect, up to 5 stacks, i.e., dealing 25 true damage per second, affected by attack multiplier, stacking resets after 5 seconds of no attacks.\n- Holding it will play a God King song, right-clicking the weapon can turn off.\n- Belongs to the Shadow category, Shadow Level 2, deals 10% more damage to the Moon faction.\n- Durability: 250, will not break when durability runs out\n- Consumes the user\'s sanity to slowly restore durability, -20san/min.\n- Repair Material: Nightmare Fuel 20%/Pure Terror 100%',''},
        gallop_brokenking = {name = 'Broken King', info_instead = '- Type: Weapon/Sword\n- Damage: 51\n- Attack Range: 1.5\n- Life Steal: 5\n- Movement Speed +10%\n- Active: [Pain Through Heaven]\n\tJump into the air and deal 100 planar damage in a 5-yard radius at the mouse position, immediately refreshes the cooldown of Fog Blade, consumes 10san, cooldown 20 seconds.\n- Passive: [Fog Blade]\n\tAttacks deal an additional 2% of the enemy\'s max health damage and restores 10 health to self, cooldown 20 seconds.\n- Passive: [Fate Sealed]\n\tWearing the Enlightenment Crown increases all damage by 100%, and reduces the cooldown of Fog Blade and Pain Through Heaven to 5 seconds.\n- Passive: [Endless Barren Land]\n\tHolding it makes you immune to the negative effects of Dark Fog and increases movement speed by an additional 10%.\n- Holding it will play the Broken King\'s song, right-clicking the weapon can turn off.\n- Belongs to the Moon faction, deals 10% more damage to the Shadow faction.\n- Durability: None\n- Displays the cooldown time of Fog Blade below the item.',''},
        gallop_ad_destroyer = {name = 'Advance Destroyer', info_instead = '- Type: Weapon/Chain Hammer\n- Damage: 102\n- Attack Range: 2.0\n- Emits a white light with a radius of 3.\n- Movement Speed +20%\n- Active: [Breakthrough Shockwave]\n\tRight-click to release a circular shockwave centered on yourself, dealing AOE damage equivalent to one basic attack, knocks back enemies in the range and slows them by 50% for 5 seconds, hitting an enemy unit increases your movement speed by 20%, stacking up to 100%, lasts for 2 seconds, cooldown 5 seconds.\n- Passive: [Crescent]\n\tAll attacks deal AOE damage.\n- Passive: [Stellar Barrier]\n\tEach attack has a 10% chance to release a hypnotic effect, hypnotizing targets in a 4-yard circular range for 12 seconds, with a 10-second cooldown.\n- Holding it will play the excavator\'s song, right-clicking the weapon can turn off.\n- Belongs to the Moon faction, deals 10% more damage to the Shadow faction.\n- Durability: 400, will not break when durability runs out\n- Repair Material: Pure Brilliance 20%',''},
        lol_wp_trinity = {
            name = 'Trinity Force',
            info_instead = '- Type: Weapon/Flying Blade/Accessory\n- Damage: '..db.TRINITY.DMG..'\n- Attack Range: '..db.TRINITY.RANGE..'\n- San Regeneration: '..db.TRINITY.DARPPERNESS..'\n- Emits a golden light with a radius of '..db.TRINITY.LIGHT_RADIUS..'.\n- Passive: [Triple Blade]\n\tAfter equipping, three blades will appear around the character, and the blades will continuously auto-attack the target the player is attacking after the character makes an attack action, dealing 3 hits.\n- After equipping, right-click to convert it into an accessory item, and wearing it will gain special passives:\n- Passive: [Ionia Spirit]\n\tMovement Speed '..((db.TRINITY.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.TRINITY.WALKSPEEDMULT-1)*100)..'%, Attack Multiplier x'..db.TRINITY.DMGMULT..', restores '..db.TRINITY.HEAL_HP..' health every '..db.TRINITY.HEAL_INTERVAL..' seconds.\n- Passive: [Triple Blade]\n\tThe blade\'s damage is reduced to '..db.TRINITY.DMG_WHEN_AMULET..', and the blade will auto-attack the target the player is attacking once after the character makes an attack action, dealing 3 hits, the accessory form will not continuously attack, and the blades will stop attacking when the character stops attacking.\n- Durability: '..db.TRINITY.FINITEUSE..', will not break when durability runs out'
        },
        lol_wp_sheen = {
            name = 'Sheen',
            info_instead = '- Type: Weapon/Sword\n- Damage: '..db.SHEEN.DMG..'\n- Movement Speed '..((db.SHEEN.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.SHEEN.WALKSPEEDMULT-1)*100)..'%'..'\n- Emits a white light with a radius of '..db.SHEEN.LIGHT_RADIUS..'.\n- Passive: [Blade]\n\tAttacks will trigger an empowered attack, dealing '..(db.SHEEN.DMGMULT*100)..'% damage, cooldown '..db.SHEEN.CD..' seconds.\n- Belongs to the Moon faction, deals '..((db.SHEEN.DMGMULT_TO_SHADOW-1)*100)..'% more damage to the Shadow faction.\n- Durability: '..db.SHEEN.FINITEUSES..', will break when durability runs out'
        },
        lol_wp_divine = {
            name = 'Divine Rapier',
            info_instead = '- Type: Weapon/Tool/Axe/Pickaxe\n- Damage: '..db.DIVINE.DMG..'\n- Attack Range: '..db.DIVINE.RANGE..'\n- Work Efficiency: Axes/Pickaxes '..(db.DIVINE.EFFICIENCY*100)..'%\n- Can mine advanced materials.\n- Movement Speed '..((db.DIVINE.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.DIVINE.WALKSPEEDMULT-1)*100)..'%'..'\n- Emits a golden light with a radius of '..db.DIVINE.LIGHT_RADIUS..'.\n- Active: [Holy Strike]\n\tRight-click to jump at the target and release a heavy strike, dealing '..(db.DIVINE.HOLY_DMG*100)..'% additional physical damage based on the target\'s max health, and restores '..db.DIVINE.HOLY_HEAL..' health to self, if attacking Shadow faction creatures (except bosses, mechanical creatures, Ink Waste) can deal 100% additional physical damage to the target\'s max health, instantly killing Shadow creatures, cooldown '..db.DIVINE.HOLY_CD..' seconds.\n- Passive: [Blade]\n\tAttacks will trigger an empowered attack, dealing '..(db.DIVINE.DMGMULT*100)..'% damage, and restores '..db.DIVINE.ATK_HEAL..' health to self, cooldown '..db.DIVINE.CD..' seconds.\n- Belongs to the Moon faction, deals '..((db.DIVINE.DMGMULT_TO_SHADOW-1)*100)..'% more damage to the Shadow faction.\n- Durability: '..db.DIVINE.FINITEUSES..', will break when durability runs out'
        },
        lol_wp_overlordbloodarmor = {
            name = 'Overlord Blood Armor',
            info_instead = '- Type: Armor\n- Defense: '..(db.OVERLORDBLOOD.ABSORB*100)..'%\n- Planar Defense: '..db.OVERLORDBLOOD.DEFEND_PLANAR..'\n- Water Resistance: '..(db.OVERLORDBLOOD.WATERPROOF*100)..'%\n- Lightning Resistance: 100%\n- When hit, triggers Bone Armor\'s damage reduction effect without consuming durability, cooldown '..db.OVERLORDBLOOD.CD..' seconds.\n- Passive: [Arrogance]\n\tConverts '..(db.OVERLORDBLOOD.SKILL_MAXHP_TO_ATK*100)..'% of player\'s maximum health to extra attack power.\n- Passive: [Retaliation]\n\tConverts '..(db.OVERLORDBLOOD.SKILL_LOSTHP_TO_ATK*100)..'% of player\'s lost health to extra attack power.\n- Passive: [Overlord\'s Divine Might]\n\tTriggers set bonus when equipped with Demonic Embrace, grants immunity to knockback and hitstun.\n- Shadow item, Shadow Level '..db.OVERLORDBLOOD.SHADOW_LEVEL..', '..db.OVERLORDBLOOD.DARPPERNESS..' san/min when worn.\n- Defeat Ancient Weavers '..(db.OVERLORDBLOOD.BLUEPRINTDROP_CHANCE.STALKER_ATRIUM*100)..'% chance to drop blueprint.\n- Durability: '..db.OVERLORDBLOOD.DURABILITY..', does not break when durability is depleted\n- When durability is below '..(db.OVERLORDBLOOD.AUTO_REPAIR.START*100)..'% it absorbs player health to repair durability, every '..db.OVERLORDBLOOD.AUTO_REPAIR.INTERVAL..' seconds -'..db.OVERLORDBLOOD.AUTO_REPAIR.DRAIN..' health, repairs '..db.OVERLORDBLOOD.AUTO_REPAIR.REPAIR..' durability.'
        },
        lol_wp_demonicembracehat = {
            name = 'Demonic Embrace',
            info_instead = '- Type: Helmet/Mask\n- Defense: '..(db.DEMONICEMBRACEHAT.ABSORB*100)..'%\n- Planar Defense: '..db.DEMONICEMBRACEHAT.DEFEND_PLANAR..'\n- Water Resistance: '..(db.DEMONICEMBRACEHAT.WATERPROOF*100)..'%\n- Lightning Resistance: 100%\n- Right-click to toggle between helmet and mask form when wearing, mask form '..db.DEMONICEMBRACEHAT.WHEN_MASKED.DARPPERNESS..' san/min, has Bone Helmet and Goggles effects, no special effects in helmet form.\n- Passive: [Dark Covenant]\n\tConverts '..(db.DEMONICEMBRACEHAT.SKILL_DARKCONVENANT.TRANSFER_MAXHP_PERCENT*100)..'% of player\'s maximum health to extra planar damage.\n- Passive: [Azakana\'s Gaze]\n\tDeals extra planar damage equal to '..(db.DEMONICEMBRACEHAT.SKILL_STARE.MAXHP_PERCENT*100)..'% of target\'s maximum health when dealing damage to an enemy, cooldown '..db.DEMONICEMBRACEHAT.SKILL_STARE.CD..' seconds.\n- Passive: [Overlord\'s Divine Might]\n\tTriggers set bonus when equipped with Overlord Blood Armor, grants immunity to knockback and hitstun.\n- Shadow item, Shadow Level '..db.DEMONICEMBRACEHAT.SHADOW_LEVEL..', '..db.DEMONICEMBRACEHAT.DARPPERNESS..' san/min when worn.\n- Defeat Ancient Weavers '..(db.DEMONICEMBRACEHAT.BLUEPRINTDROP_CHANCE.STALKER_ATRIUM*100)..'% chance to drop blueprint.\n- Durability: '..db.DEMONICEMBRACEHAT.DURABILITY..', does not break when durability is depleted\n- When durability is low, absorbs player sanity to repair durability, similar to Despair Stone.'
        },
        lol_wp_warmogarmor = {
            name = 'Warmog Armor',
            info_instead = '- Type: Armor\n- Defense: '..(db.WARMOGARMOR.ABSORB*100)..'%\n- Insulation: '..db.WARMOGARMOR.INSULATION..'\n- Water Resistance: '..(db.WARMOGARMOR.WATERPROOF*100)..'%\n- Spirit Regeneration: '..db.WARMOGARMOR.DARPPERNESS..'\n- Hunger Speed -'..((1-db.WARMOGARMOR.HUNGERRATE)*100)..'%\n- Movement Speed '..((db.WARMOGARMOR.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.WARMOGARMOR.WALKSPEEDMULT-1)*100)..'%'..'\n- Active: [Fungal Fog]\n\tSummons a spore cloud at the player\'s location, identical to a sleeping bag, consumes '..db.WARMOGARMOR.SKILL_POISONFOG.CONSUME_FINITEUSE..' durability, cooldown '..db.WARMOGARMOR.SKILL_POISONFOG.CD..' seconds.\n- Passive: [Warmog\'s Heart]\n\tIf the player does not take damage for '..db.WARMOGARMOR.SKILL_HEART.NO_TAKE_DMG_IN..' seconds and health is below '..(db.WARMOGARMOR.SKILL_HEART.HP_PERCENT_BELOW*100)..'% then regenerates '..(db.WARMOGARMOR.SKILL_HEART.REGEN_PERCENT*100)..'% of maximum health every '..db.WARMOGARMOR.SKILL_HEART.INTERVAL..' seconds and increases movement speed by '..(db.WARMOGARMOR.SKILL_HEART.WALKSPEEDMULT*100)..'% without consuming durability when Warmog\'s Heart is triggered, consumes '..db.WARMOGARMOR.SKILL_HEART.RESUME..' durability per second.\n- Passive: [Go Wherever You Want]\n\tGrants immunity to knockback when worn.\n- Emits green mushroom spores when worn.\n- Defeat Wretched Toadstool '..(db.WARMOGARMOR.BLUEPRINTDROP_CHANCE.TOADSTOOL_DARK*100)..'% chance to drop blueprint, Defeated Toadstool '..(db.WARMOGARMOR.BLUEPRINTDROP_CHANCE.TOADSTOOL*100)..'% chance to drop blueprint.\n- Durability: '..db.WARMOGARMOR.DURABILITY..', does not break when durability is depleted'
        },
        lol_wp_s8_deathcap = {
            name = 'Deathcap of the Worldbreaker',
            info_instead = '- Type: Hat\n- Water Resistance: '..(db.DEATHCAP.WATERPROOF*100)..'%\n- Lightning Resistance: 100%\n- Functions like a Mage\'s Top Hat, can be used by characters other than Maxwell.\n- Emits a blue light with a radius of '..db.DEATHCAP.LIGHT_RADIUS..'.\n- Passive: [Magical Overture]\n\tAttacks deal additional '..db.DEATHCAP.SKILL_MAGIC.WEAR_INCREASE_PLANAR_DMG..' planar damage, increases planar damage dealt by '..((db.DEATHCAP.SKILL_MAGIC.WEAR_INCREASE_PLANAR_DMG_MULT-1)*100)..'% when worn.\n- Shadow item, Shadow Level '..db.DEATHCAP.SHADOW_LEVEL..', increases damage dealt to Shadow enemies by '..((db.DEATHCAP.WEAR_INCREASE_SHADOW_WEAPON_DMGMULT-1)*100)..'% when using Shadow items, '..db.DEATHCAP.DARPPERNESS..' san/min when worn.\n- Durability: None'
        },
        lol_wp_s8_uselessbat = {
            name = 'Useless Bat',
            info_instead = '- Type: Weapon/Tool/Hammer\n- Attack Power: '..db.USELESSBAT.DMG..'\n- Planar Damage: '..db.USELESSBAT.PLANAR_DMG..'\n- Work Efficiency: Hammer 100%\n- Shadow item, Shadow Level '..db.USELESSBAT.SHADOW_LEVEL..', increases damage dealt to Moon enemies by '..((db.USELESSBAT.DMGMULT_TO_PLANAR-1)*100)..'% when held, '..db.USELESSBAT.DARPPERNESS..' san/min when held.\n- Durability: '..db.USELESSBAT.FINITEUSE..', breaks when durability is depleted'
        },
        lol_wp_s8_lichbane = {
            name = 'Lichbane',
            info_instead = '- Type: Weapon/Sword\n- Planar Damage: '..db.LICHBANE.PLANAR_DMG..'\n- Emits a golden light with a radius of '..db.LICHBANE.LIGHT_RADIUS..'.\n- Movement Speed '..((db.LICHBANE.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.LICHBANE.WALKSPEEDMULT-1)*100)..'%'..'\n- Passive: [Curse Blade]\n\tAttacks trigger a strengthened attack dealing '..(db.LICHBANE.SKILL_CURSEBLADE.DMGMULT*100)..'% damage, cooldown '..db.LICHBANE.SKILL_CURSEBLADE.CD..' seconds.\n- Passive: [Source of Malice]\n\tAttacked targets gain '..((db.LICHBANE.SKILL_CURSERACE.DMGMULT-1)*100)..'% vulnerability for '..db.LICHBANE.SKILL_CURSERACE.LAST..' seconds, attacks ignite targets, dealing '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_DMG..' fire damage every '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_PERIOD..' seconds for '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_LAST..' seconds.\n- Defeat Mutated Warg '..(db.LICHBANE.DROP_CHANCE.mutatedwarg*100)..'% chance to drop a finished item\n- Shadow item, Shadow Level '..db.LICHBANE.SHADOW_LEVEL..', '..db.LICHBANE.DARPPERNESS..' san/min when held, increases damage dealt to Moon enemies by '..((db.LICHBANE.DMGMULT_TO_PLANAR-1)*100)..'%.\n- Durability: '..db.LICHBANE.FUELED..' minutes, durability does not decrease with attacks but over time, does not break when durability is depleted but the sword\'s flames disappear and the light vanishes. Can be equipped but only deals '..db.LICHBANE.DMG_WHEN_NO_DURABILITY..' physical damage and does not trigger any special effects.'
        },
        lol_wp_s9_guider = {
            name = 'Guide',
            info_instead = '- Type: Container/Backpack\n- Capacity: 14\n- Defense: '..(db.GUIDER.ABSORB*100)..'%\n- Warmth: '..db.GUIDER.AVOID_COLD..'\n- Water Resistance: '..(db.GUIDER.WATERPROOF*100)..'%\n- Spirit Recovery: '..db.GUIDER.DARPPERNESS..'\n- Emits a radius '..db.GUIDER.LIGHT.RADIUS..' of golden light.\n- Has a refrigerator preservation effect.\n- Fireproof, will not catch fire.\n- Movement speed '..((db.GUIDER.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.GUIDER.WALKSPEEDMULT-1)*100)..'%'..'\n- Passive: [Guide]\n\tProvides '..((db.GUIDER.SKILL_GUIDE.WALKSPEEDMULT-1)*100)..'% movement speed boost to players within a radius '..db.GUIDER.SKILL_GUIDE.RADIUS..'. Does not stack with multiple equips. Attacking enemies applies '..(db.GUIDER.SKILL_GUIDE.ATK_SPEEDDOWN*100)..'% slow for '..db.GUIDER.SKILL_GUIDE.LAST..' seconds, cooldown '..db.GUIDER.SKILL_GUIDE.CD..' seconds.\n- Durability: None'
        },
        lol_wp_s9_eyestone_low = {
            name = 'Guardian Eye Stone',
            info_instead = '- Type: Container/Amulet\n- Passive: [Arcane Cache]\n\tWearing it provides 3 additional amulet slots, similar to fusion medals, can hold League of Legends weapon amulets, cannot hold container amulets, cannot equip two of the same amulet at the same time, all equipped amulets will take effect simultaneously.\n- Passive: [Balance]\n\tAll amulets placed in the eye stone reduce the extra physical/planar damage provided by '..((1-db.ITEM_EFFECT_RATE_IN_EYESTONE)*100)..'% of the amulets, can be adjusted in mod settings.\n- Durability: None'
        },
        lol_wp_s9_eyestone_high = {
            name = 'Alert Eye Stone',
            info_instead = '- Type: Container/Amulet\n- Passive: [Arcane Cache]\n\tWearing it provides 6 additional amulet slots, similar to fusion medals, can hold League of Legends weapon amulets, cannot hold container amulets, cannot equip two of the same amulet at the same time, all equipped amulets will take effect simultaneously.\n- Passive: [Balance]\n\tAll amulets placed in the eye stone reduce the extra physical/planar damage provided by '..((1-db.ITEM_EFFECT_RATE_IN_EYESTONE)*100)..'% of the amulets, can be adjusted in mod settings.\n- Durability: None'
        },
        lol_wp_s10_guinsoo = {
            name = "Guinsoo's Rageblade",
            info_instead = '- Type: Weapon/Dagger\n- Attack Power: '..db.GUINSOO.DMG..'\n- Planar Damage: '..db.GUINSOO.PLANAR_DMG..'\n- Active: [Whirlwind Strike]\n\tStabs in a specified direction, dealing '..db.GUINSOO.SKILL_ALPHA.DMG..' damage and '..db.GUINSOO.SKILL_ALPHA.PLANAR_DMG..' planar damage to enemies on the path, cooldown '..db.GUINSOO.SKILL_ALPHA.CD..' seconds.\n- Passive: [Boil Strike]\n\tEach attack increases attack speed by '..(db.GUINSOO.SKILL_BOILSTRIKE.SPEED_PER*100)..'% up to '..db.GUINSOO.SKILL_BOILSTRIKE.MAXSTACK..' stacks, providing a maximum of '..(db.GUINSOO.SKILL_BOILSTRIKE.SPEED_PER*db.GUINSOO.SKILL_BOILSTRIKE.MAXSTACK*100)..'% attack speed, lasts '..db.GUINSOO.SKILL_BOILSTRIKE.COMBO_KEEPTIME..' seconds.\n- When fully stacked, it continuously heats up, equivalent to a Dragon Scale Furnace, emitting a radius '..db.GUINSOO.LIGHT.RADIUS..' of golden light, attacks will ignite targets, dealing '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_DMG..' fire damage every '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_PERIOD..' seconds for '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_LAST..' seconds.\n- Defeating Dragonfly '..(db.GUINSOO.BLUEPRINTDROP_CHANCE.dragonfly*100)..'% chance to drop blueprint.\n- Plays a small tune when held, right-clicking the weapon can turn it off.\n- Defeating Armored Badger '..(db.GUINSOO.DROP_CHANCE.mutatedbearger*100)..'% chance to drop a finished product\n- Durability: '..db.GUINSOO.FINITEUSE..', does not break when durability is depleted'
        },
        lol_wp_s10_blastingwand = {
            name = 'Blasting Wand',
            info_instead = '- Type: Weapon/Wand\n- Planar Damage: '..db.BLASTINGWAND.PLANAR_DMG..'\n- Attack Range: '..db.BLASTINGWAND.RANGE..'\n- Attacks ignite targets, dealing '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_DMG..' fire damage every '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_PERIOD..' seconds for '..db.GUINSOO.SKILL_BOILSTRIKE.WHEN_MAXSTACK_BURN_LAST..' seconds.\n- Belongs to Shadow item, Shadow Level '..db.BLASTINGWAND.SHADOW_LEVEL..', consumes '..db.BLASTINGWAND.DARPPERNESS..'san/min when held, increases damage to Moon faction by '..((db.BLASTINGWAND.DMGMULT_TO_PLANAR-1)*100)..'%.\n- Durability: '..db.BLASTINGWAND.FINITEUSE..', breaks when durability is depleted'
        },
        lol_wp_s10_sunfireaegis = {
            name = 'Sunfire Aegis',
            info_instead = '- Type: Weapon/Shield/Armor\n- Attack Power: '..db.SUNFIREAEGIS.DMG..'\n- Defense: '..(db.SUNFIREAEGIS.ABSORB*100)..'%\n- Warmth: '..db.SUNFIREAEGIS.AVOID_COLD..'\n- Immune to fire damage.\n- Movement speed '..((db.SUNFIREAEGIS.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.SUNFIREAEGIS.WALKSPEEDMULT-1)*100)..'%'..'\n- Active: [Sun Shelter]\n\tRight-click and select a direction to block attacks from that direction for 3 seconds, blocking does not consume durability. When blocking successfully, deals '..db.SUNFIREAEGIS.SKILL_SUNSHELTER.SUCCESS_BLOCK.PLANAR_DMG..' planar damage and '..(db.SUNFIREAEGIS.SKILL_SUNSHELTER.SUCCESS_BLOCK.EXTRA_DMG_OF_MAXHEALTH*100)..'% of your max health as additional planar damage to enemies within a radius of '..db.SUNFIREAEGIS.SKILL_SUNSHELTER.SUCCESS_BLOCK.RANGE..' meters.\n- Passive: [Sacrifice]\n\tWhen equipped, a red circle appears under the character. Enemies within a radius of '..db.SUNFIREAEGIS.SKILL_SACRIFICE.RANGE..' meters of the character take '..db.SUNFIREAEGIS.SKILL_SACRIFICE.PER_PLANARDMG..' planar damage and 5% of your max health as additional planar damage every '..db.SUNFIREAEGIS.SKILL_SACRIFICE.INTERVAL..' seconds.\n- Passive: [Flame Touch]\n\tAttacks ignite enemies, dealing '..db.SUNFIREAEGIS.SKILL_FIRETOUCH.BURN_DMG..' fire damage every '..db.SUNFIREAEGIS.SKILL_FIRETOUCH.BURN_PERIOD..' seconds for '..db.SUNFIREAEGIS.SKILL_FIRETOUCH.BURN_LAST..' seconds.\n- Right-click when equipped to change form, name changes to [Sunfire Cloak], can be used as armor, stats remain the same, and triggers the [Sacrifice] effect. Equipping both Sunfire Aegis and Sunfire Cloak will only trigger [Sacrifice] once, and [Flame Touch] changes to ignite targets when attacked, similar to scale armor.\n- Defeating Dragonfly '..(db.GUINSOO.BLUEPRINTDROP_CHANCE.dragonfly*100)..'% chance to drop blueprint.\n- Durability: '..db.SUNFIREAEGIS.FINITEUSE..', does not break when durability is depleted'
        },
        lol_wp_s11_amplifyingtome = {
            name = 'Amplifying Tome',
            info_instead = '- Type: Amulet/Magic Book\n- Extra Planar Damage: '..db.AMPLIFYINGTOME.PLANAR_DMG..'\n- Can be placed in a bookshelf to restore durability.\n- Active: [Apocalypse]\n\tWhen equipped, characters with reading ability can read it, summoning 16 lightning bolts around the character, same effect as "Apocalypse!", consumes '..(db.AMPLIFYINGTOME.CONSUME_WHEN_READ*100)..'% of durability upon use.\n- Belongs to Shadow item, Shadow Level 2.\n- Durability: '..db.AMPLIFYINGTOME.FINITEUSES..', breaks when durability is depleted'
        },
        lol_wp_s11_darkseal = {
            name = 'Dark Seal',
            info_instead = '- Type: Amulet/Ring\n- Extra Planar Damage: '..db.DARKSEAL.PLANAR_DMG..'\n- Cannot be equipped with Mejai\'s Soulstealer simultaneously.\n- Passive: [Honor]\n\tGain '..db.DARKSEAL.SKILL_HONOR.STACK_PER_BOSSSKILL..' layers of passive for each boss mob killed, each layer provides '..db.DARKSEAL.SKILL_HONOR.EXTRA_PLANAR_DMG_PER_STACK..' extra planar damage, up to '..db.DARKSEAL.SKILL_HONOR.MAXSTACK..' layers, totaling 25 extra planar damage. Passive layers are cleared upon death while equipped.\n- Belongs to Shadow item, Shadow Level '..db.DARKSEAL.SHADOW_LEVEL..', consumes '..db.DARKSEAL.DARPPERNESS..'san/min when equipped.\n- Durability: None\n- Displays the number of stacked layers below the item.'
        },
        lol_wp_s11_mejaisoulstealer = {
            name = 'Mejai\'s Soulstealer',
            info_instead = '- Type: Amulet/Magic Book\n- Extra Planar Damage: '..db.MEJAISOULSTEALER.PLANAR_DMG..'\n- Inherits passive layers from Dark Seal when crafted, cannot be equipped with Dark Seal simultaneously.\n- Passive: [Honor]\n\tGain '..db.MEJAISOULSTEALER.SKILL_HONOR.BOSSKILL_BY_SELF_STACK..' layers of passive for each boss mob killed by yourself, '..db.MEJAISOULSTEALER.SKILL_HONOR.STACK_PER_BOSSSKILL..' layers for each boss mob killed with assistance, each layer provides '..db.MEJAISOULSTEALER.SKILL_HONOR.EXTRA_PLANAR_DMG_PER_STACK..' extra planar damage, up to '..db.MEJAISOULSTEALER.SKILL_HONOR.MAXSTACK..' layers, totaling 50 extra planar damage. Passive layers are cleared upon death while equipped.\n- Belongs to Shadow item, Shadow Level '..db.MEJAISOULSTEALER.SHADOW_LEVEL..', consumes '..db.MEJAISOULSTEALER.DARPPERNESS..'san/min when equipped.\n- Durability: None\n- Displays the number of stacked layers below the item.'
        },
        lol_wp_s12_eclipse = {
            name = 'Eclipse',
            info_instead = '- Type: Weapon/Dagger\n- Attack Power: '..db.ECLIPSE.DMG..'\n- Attack Range: '..db.ECLIPSE.RANGE..'\n- Spirit Recovery: '..db.ECLIPSE.DARPPERNESS..'\n- Emits a radius '..db.ECLIPSE.LIGHT.RADIUS..' meters of blue light\n- Movement speed '..((db.ECLIPSE.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.ECLIPSE.WALKSPEEDMULT-1)*100)..'%'..'\n- Active: [New Moon Strike]\n\tRight-click to release '..db.ECLIPSE.SKILL_NEWMOON_STRIKE.LASER_NUM..' laser beams from the current position, consumes '..db.ECLIPSE.SKILL_NEWMOON_STRIKE.CONSUME_SAN..' sanity, each beam deals '..db.ECLIPSE.SKILL_NEWMOON_STRIKE.LASER_PLANAR_DMG..' planar damage, destroys minerals and trees on the path, does not destroy buildings, cooldown '..db.ECLIPSE.SKILL_NEWMOON_STRIKE.CD..' seconds.\n- Passive: [Evermoon]\n\tEvery '..db.ECLIPSE.SKILL_EVERMOON.ATK_COUNT_DO_EXTRA..' attacks deal '..(db.ECLIPSE.SKILL_EVERMOON.ENEMY_MAXHP_RATE_PLANAR_DMG*100)..'% of the enemy\'s max health as extra planar damage and grants you an invulnerable shield for '..db.ECLIPSE.SKILL_EVERMOON.SHIELD_DURATION..' seconds, cooldown '..db.ECLIPSE.SKILL_EVERMOON.CD..' seconds.\n- Belongs to Moon faction, increases damage to Shadow faction by '..((db.ECLIPSE.DMGMULT_TO_SHADOW-1)*100)..'%.\n- Equipping with Bright Bell Helmet and Bright Bell Armor simultaneously grants the weapon an electrified effect.\n- Defeating Celestial Hero '..(db.ECLIPSE.BLUEPRINTDROP_CHANCE.alterguardian_phase3*100)..'% chance to drop blueprint.\n- Durability: None\n- Displays the cooldown time of Evermoon below the item.'
        },
        lol_wp_s12_malignance = {
            name = 'Malignance',
            info_instead = '- Type: Weapon/Lance\n- Attack Power: '..db.MALIGNANCE.DMG..'\n- Attack Range: '..db.MALIGNANCE.RANGE..'\n- Movement speed '..((db.MALIGNANCE.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.MALIGNANCE.WALKSPEEDMULT-1)*100)..'%'..'\n- Active: [Fallen Blow]\n\tJump to the air and deal '..db.MALIGNANCE.SKILL_FALLEN_BLOW.DAMAGE..' physical damage in a radius of '..db.MALIGNANCE.SKILL_FALLEN_BLOW.RADIUS..' meters at the mouse position, but does not trigger [Glow Shield Strike]. Destroys minerals and trees in the area, does not destroy buildings, cooldown '..db.MALIGNANCE.SKILL_FALLEN_BLOW.CD..' seconds.\n- Passive: [Glow Shield Strike]\n\tThe first attack on a target deals a triple hit, and if the target is a boss, it heals you '..db.MALIGNANCE.SKILL_GLOWSHIELD_STRIKE.HEAL_HP..' health and '..(db.MALIGNANCE.SKILL_GLOWSHIELD_STRIKE.HEAL_LOST_RATE_HP*100)..'% of lost health, each target has its own cooldown of '..db.MALIGNANCE.SKILL_GLOWSHIELD_STRIKE.CD_PER_TARGET..' seconds.\n- Belongs to Moon faction, increases damage to Shadow faction by '..((db.MALIGNANCE.DMGMULT_TO_SHADOW-1)*100)..'%.\n- Durability: '..db.MALIGNANCE.FINITEUSES..', does not break when durability is depleted'
        },
        alchemy_chainsaw = {name = 'Alchemy Punk Chainsaw Sword', info_instead = '- Type: Weapon/Tool/Chainsaw\n- Attack Power: 51\n- Movement speed +10%\n- Active: [Chainsaw Start]\n\tRight-click to activate the chainsaw, increasing attack power to 68, consuming 1 durability every 2 seconds, can trigger [Mercy] and [Lacerate], can quickly chop trees, right-click again to deactivate.\n- Work Efficiency: Axe: 1000%\n- Active: [Mercy]\n\tUnlocks right-click skill after activating the chainsaw, consumes 10 health points, right-clicking the target jumps and strikes for double the weapon\'s current attack power damage, immediately settling bleed damage, dealing additional damage equal to (bleed damage x bleed stacks x remaining time), and clears all bleed stacks on the target. If the target\'s health is reduced to 25%/8% (normal mob/BOSS) or below, it will be instantly killed and restore 15 sanity and 15 health points, cooldown 20 seconds.\n- Passive: [Lacerate]\n\tEach attack applies a bleed effect and 60% grievous wound effect (reduces target\'s healing by 60%), dealing 2 damage per second for 20 seconds, stacking up to 10 layers with each attack, causing a maximum of 20 damage per second, affected by attack multipliers.\n- Defeating Scavenger Pig 100% chance to drop blueprint.\n- Durability: 400, does not break when durability is depleted, can be equipped but attack power becomes 34.\n- Repair Materials: Gears 20%/Auto Repair Machine 100%'},
        lol_wp_s13_infinity_edge = {
            name = 'Infinity Edge',
            info_instead = '- Type: Weapon/Sword/Amulet\n- Attack Power: '..db.INFINITY_EDGE.DMG..'\n- Attack Range: '..db.INFINITY_EDGE.RANGE..'\n- '..(db.INFINITY_EDGE.CRITICAL_CHANCE*100)..'% chance to deal '..db.INFINITY_EDGE.CRITICAL_DMGMULT..' times damage.\n- Passive: [Infinity Power]\n\tIncreases attack multiplier by '..((db.INFINITY_EDGE.SKILL_INFINITY_EDGE.OWNER_DMGMULT_WHEN_EQUIP-1)*100)..'% when equipped.\n- Right-click after equipping to convert to an amulet item, wearing it grants special passive:\n- Passive: [Infinity Power]\n\tIncreases attack multiplier by '..((db.INFINITY_EDGE.AS_AMULET.OWNER_DMGMULT_WHEN_EQUIP-1)*100)..'% when equipped, '..db.INFINITY_EDGE.AS_AMULET.DARPPERNESS..'san/min, increases critical hit chance by '..(db.INFINITY_EDGE.AS_AMULET.CRITICAL_CHANCE*100)..'% and critical damage by '..((db.INFINITY_EDGE.AS_AMULET.CRITICAL_DMGMULT-1)*100)..'% for all weapons, allowing all weapons to trigger critical hits, but critical damage is only 1.5 times.\n- Planar damage does not trigger critical hits.\n- Durability: '..db.INFINITY_EDGE.FINITEUSES..', does not break when durability is depleted'
        },
        lol_wp_s13_statikk_shiv = {
            name = 'Statikk Shiv',
            info_instead = '- Type: Weapon/Sword\n- Attack Power: '..db.STATIKK_SHIV.DMG..'\n- Attacks electrify targets, dealing 1.5 times damage, 2.5 times damage to wet targets.\n- '..(db.STATIKK_SHIV.CRITICAL_CHANCE*100)..'% chance to deal '..db.STATIKK_SHIV.CRITICAL_DMGMULT..' times damage.\n- Movement speed '..((db.STATIKK_SHIV.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.STATIKK_SHIV.WALKSPEEDMULT-1)*100)..'%'..'\n- Passive: [Electric Spark]\n\tThe first '..db.STATIKK_SHIV.SKILL_ELECTRIC_SPARK.HIT_TIMES..' hits launch chain lightning, chaining to the nearest unit within '..db.STATIKK_SHIV.SKILL_ELECTRIC_SPARK.CHAIN_RANGE..' meters and dealing '..db.STATIKK_SHIV.SKILL_ELECTRIC_SPARK.PLANAR_DMG_WHEN_CHAIN..' planar damage, up to '..db.STATIKK_SHIV.SKILL_ELECTRIC_SPARK.CHAIN_MAX_TARGET..' targets, each target can only be chained once, cooldown '..db.STATIKK_SHIV.SKILL_ELECTRIC_SPARK.CD..' seconds.\n- Passive: [Charge]\n\tEach attack reduces '..db.STATIKK_SHIV.SKILL_CHARGE.REDUCE_SKILL_ELECTRIC_SPARK_PER_HIT..' seconds of passive skill cooldown.\n- Functions as a lightning rod when placed on the ground, prioritizing lightning strikes, turning into [Statikk Shiv Blade] after being struck by lightning.\n- Durability: '..db.STATIKK_SHIV.FINITEUSES..', does not break when durability is depleted\n- Left-clicking the lightning rod or generator with the weapon repairs 100% durability and consumes 1 charge/energy.'
        },
        lol_wp_s13_statikk_shiv_charged = {
            name = 'Statikk Shiv Blade',
            info_instead = '- Type: Weapon/Dagger\n- Attack Power: '..db.STATIKK_SHIV_CHARGED.DMG..'\n- Attacks electrify targets, dealing 1.5 times damage, 2.5 times damage to wet targets.\n- '..(db.STATIKK_SHIV_CHARGED.CRITICAL_CHANCE*100)..'% chance to deal '..db.STATIKK_SHIV_CHARGED.CRITICAL_DMGMULT..' times damage.\n- Emits a radius '..db.STATIKK_SHIV_CHARGED.LIGHT.RADIUS..' of white light.\n- Movement speed '..((db.STATIKK_SHIV_CHARGED.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.STATIKK_SHIV_CHARGED.WALKSPEEDMULT-1)*100)..'%'..'\n- Passive: [Electric Spark]\n\tEach attack launches chain lightning, chaining to the nearest unit within '..db.STATIKK_SHIV_CHARGED.SKILL_ELECTRIC_SPARK.CHAIN_RANGE..' meters and dealing '..db.STATIKK_SHIV_CHARGED.SKILL_ELECTRIC_SPARK.PLANAR_DMG_WHEN_CHAIN..' planar damage, up to '..db.STATIKK_SHIV_CHARGED.SKILL_ELECTRIC_SPARK.CHAIN_MAX_TARGET..' targets, each target can only be chained once, no cooldown.\n- Functions as a lightning rod when placed on the ground, prioritizing lightning strikes, restoring full durability after being struck by lightning.\n- Durability: '..db.STATIKK_SHIV_CHARGED.FINITEUSES..', turns back into [Statikk Shiv] when durability is depleted\n- Left-clicking the lightning rod or generator with the weapon repairs 100% durability and consumes 1 charge/energy.',
        },
        lol_wp_s13_collector = {
            name = 'Collector',
            info_instead = '- Type: Weapon/Rifle\n- Attack Power: '..db.COLLECTOR.DMG..'\n- Attack Speed: 0.5\n- Attack Range: '..db.COLLECTOR.RANGE..'\n- '..(db.COLLECTOR.CRITICAL_CHANCE*100)..'% chance to deal '..db.COLLECTOR.CRITICAL_DMGMULT..' times damage.\n- Has one ammo slot, requires gold blocks as ammunition, consumes 1 per attack, cannot attack without ammunition.\n- Passive: [Death and Tax]\n\tIf the damage you deal reduces an enemy\'s health to '..(db.COLLECTOR.SKILL_DEATH_AND_TAX.SEC_KILL_HP_LINE*100)..'% or below, it will be instantly killed and deal '..db.COLLECTOR.SKILL_DEATH_AND_TAX.PLANAR_DMG_WHEN_SEC_KILL..' planar damage. Killing boss mobs provides an additional '..db.COLLECTOR.SKILL_DEATH_AND_TAX.GOLDNUGGET_WHEN_KILL_BOSS..' gold blocks, killing normal mobs drops '..db.COLLECTOR.SKILL_DEATH_AND_TAX.GOLDNUGGET_WHEN_KILL_NORMAL..' gold blocks.\n- Has a chance to drop from ocean chests, the probability increases with the world day number, starting at '..(db.COLLECTOR.DROP_FROM_OCEANCHEST.START_CHANCE*100)..'% on Day 1, reaching a maximum of '..(db.COLLECTOR.DROP_FROM_OCEANCHEST.MAX_CHANCE*100)..'% on Day '..db.COLLECTOR.DROP_FROM_OCEANCHEST.MAX_DAY..'.\n- Durability: None'
        },
        lol_wp_s14_bramble_vest = {
            name = 'Bramble Vest',
            info_instead = '- Type: Armor\n- Defense: '..(db.BRAMBLE_VEST.ABSORB*100)..'%\n- Water Resistance: '..(db.BRAMBLE_VEST.WATERPROOF*100)..'%\n- Passive: [Bramble]\n\tWhen equipped, reflects '..(db.BRAMBLE_VEST.SKILL_BRAMBLE.REFLECT_DMG_PERCENT*100)..'% of enemy damage as planar damage back to the attacker, similar to Bramble Shell. Reflected damage targets take '..(db.BRAMBLE_VEST.SKILL_BRAMBLE.REFLECTED_TARGET_DMGTAKEN*100)..'% increased damage for '..db.BRAMBLE_VEST.SKILL_BRAMBLE.DMGTAKEN_LAST..' seconds.\n- Durability: '..db.BRAMBLE_VEST.FINITEUSES..', breaks when durability is depleted',
        },
        lol_wp_s14_thornmail = {
            name = 'Thornmail',
            info_instead = '- Type: Armor\n- Defense: '..(db.THORNMAIL.ABSORB*100)..'%\n- Water Resistance: '..(db.THORNMAIL.WATERPROOF*100)..'%\n- Movement speed '..((db.THORNMAIL.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.THORNMAIL.WALKSPEEDMULT-1)*100)..'%'..'\n- Passive: [Bramble]\n\tWhen equipped, reflects '..(db.THORNMAIL.SKILL_BRAMBLE.REFLECT_DMG_PERCENT*100)..'% of enemy damage as planar damage back to the attacker, similar to Bramble Shell. Reflected damage targets take '..(db.THORNMAIL.SKILL_BRAMBLE.REFLECTED_TARGET_DMGTAKEN*100)..'% increased damage for '..db.THORNMAIL.SKILL_BRAMBLE.DMGTAKEN_LAST..' seconds.\n- Belongs to Shadow item, Shadow Level '..db.THORNMAIL.SHADOW_LEVEL..', consumes '..db.THORNMAIL.DARPPERNESS..'san/min when equipped.\n- Defeating Nightmare Pig '..(db.THORNMAIL.BLUEPRINTDROP_CHANCE.daywalker*100)..'% chance to drop blueprint.\n- Durability: '..db.THORNMAIL.FINITEUSES..', does not break when durability is depleted\n- Absorbs player sanity to restore durability when durability is low, similar to Despair Stone.',
        },
        lol_wp_s14_hubris = {
            name = 'Hubris',
            info_instead = '- Type: Helmet/Crown\n- Defense: '..(db.HUBRIS.ABSORB*100)..'%\n- Extra Attack Power: '..db.HUBRIS.DMG_WHEN_EQUIP..'\n- Movement speed '..((db.HUBRIS.WALKSPEEDMULT - 1) >= 0 and '+' or '')..((db.HUBRIS.WALKSPEEDMULT-1)*100)..'%'..'\n- Passive: [Reputation]\n\tGains '..db.HUBRIS.SKILL_REPUTATION.BOSSKILL_BY_SELF_STACK..' layers of passive for each boss mob killed, each layer provides '..db.HUBRIS.SKILL_REPUTATION.DMG_PER_STACK..' attack power, max '..(not db.HUBRIS.SKILL_REPUTATION.MAXSTACK and 'unlimited' or db.HUBRIS.SKILL_REPUTATION.MAXSTACK)..' layers, can be set to unlimited in mod settings.\n- Belongs to Shadow item, Shadow Level '..db.HUBRIS.SHADOW_LEVEL..', consumes '..db.HUBRIS.DARPPERNESS..'san/min when equipped.\n- Defeating Queen Bee '..(db.HUBRIS.BLUEPRINTDROP_CHANCE.beequeen*100)..'% chance to drop blueprint.\n- Durability: None\n- Displays the number of stacked layers below the item.',
        },
        lol_wp_s15_crown_of_the_shattered_queen = {
            name = 'Crown of the Shattered Queen',
            info_instead = '- Type: Helmet/Crown\n- Defense: '..(db.CROWN_OF_THE_SHATTERED_QUEEN.ABSORB*100)..'%\n- Planar Defense: '..db.CROWN_OF_THE_SHATTERED_QUEEN.DEFEND_PLANAR..'\n- Additional Planar Damage: '..db.CROWN_OF_THE_SHATTERED_QUEEN.PLANAR_DMG_WHEN_EQUIP ..'\n- Sanity Regeneration: '..db.CROWN_OF_THE_SHATTERED_QUEEN.DARPPERNESS..'\n- Passive: [Guard]\n\tGenerates a shield similar to a Thulium Crown when equipped, immune to all damage, infinite duration, doubles sanity regeneration speed during shield duration, disappears '..db.CROWN_OF_THE_SHATTERED_QUEEN.SKILL_GUARD.FADE_WHEN_ATTACKED..' seconds after being attacked, cooldown '..db.CROWN_OF_THE_SHATTERED_QUEEN.SKILL_GUARD.CD..' seconds.\n- Passive: [Mourn]\n\tIncreases damage by '..((db.CROWN_OF_THE_SHATTERED_QUEEN.SKILL_MOURN.DMGMULT-1)*100)..'% when equipped with the Blade of the Broken King.\n- Belongs to the Moon faction.\n- Durability: None',
        },
        lol_wp_s15_stopwatch = {
            name = 'Stopwatch',
            info_instead = '- Type: Special Item\n- Used for short-distance instant teleportation. When the player has a stopwatch, small time nodes are generated along the player\'s path.\n- Active: [Traceback]\n\tRight-clicking the item teleports the player to the location of a time node. Cooldown '..db.STOPWATCH.SKILL_TRACEBACK.CD..' seconds. Functionality identical to Wanda\'s Rewind Watch, but usable by other characters.\n- Active: [Temporal Rift]\n\tWhen Wanda uses it, right-clicking the item teleports to a time node and deals '..db.STOPWATCH.SKILL_JIKU.PLANAR_DMG..' area planar damage, triggering the effect of the Hourglass, restoring time value, cooldown '..db.STOPWATCH.SKILL_JIKU.CD..' seconds.\n- Durability: None',
        },
        lol_wp_s15_zhonya = {
            name = 'Zhonya\'s Hourglass',
            info_instead = '- Type: Amulet/Special Item\n- Additional Planar Damage: '..db.ZHONYA.PLANAR_DMG_WHEN_EQUIP..'\n- Defense: '..(db.ZHONYA.ABSORB*100)..'%\n- Sanity Regeneration: '..db.ZHONYA.DARPPERNESS..'\n- Active: [Stasis]\n\tRight-clicking the item when equipped grants immunity to all damage, including burning, hunger, and extreme temperatures for '..db.ZHONYA.SKILL_FREEZE.DURATION..' seconds, turning the character golden during invincibility, allowing normal movement and attacks. Trigger with '..keymap[TUNING[string.upper('CONFIG_'..modid..'key_lol_wp_s15_zhonya_freeze')]]..' key, adjustable in mod settings. Cooldown '..db.ZHONYA.SKILL_FREEZE.CD..' seconds after use.\n- Passive: [Eternal]\n\tWanda or characters with time value equipped will not lose time value automatically, but will still lose time when taking damage.\n- Belongs to the Moon faction.\n- Durability: None',
        },
        lol_wp_s16_potion_hp = {
            name = 'Health Potion',
            info_instead = '- Type: Special Item/Potion\n- Consumable, stackable up to 20.\n- Effects upon consumption:\n\tHealth '..(db.POTION_HP.DRINK_HP > 0 and '+' or '-')..(math.abs(db.POTION_HP.DRINK_HP))..', Sanity '..(db.POTION_HP.DRINK_SAN > 0 and '+' or '-')..(math.abs(db.POTION_HP.DRINK_SAN))..', provides '..db.POTION_HP.DRINK_PERSEC_HP..' Health per 2 seconds for '..db.POTION_HP.DURATION..' seconds, stacking only duration, not speed, up to '..(db.POTION_HP.MAX/db.POTION_HP.DURATION)..' layers ('..db.POTION_HP.MAX..' seconds). Stacking to max will not increase duration further.\n- Cannot be used with Corruption Potion or Compound Potion simultaneously.\n- Consumable.',
        },
        lol_wp_s16_potion_compound = {
            name = 'Compound Potion',
            info_instead = '- Type: Special Item/Potion\n- Consumable, non-stackable.\n- \n- Effects upon consumption:\n\tHealth '..(db.POTION_COMPOUND.DRINK_HP > 0 and '+' or '-')..(math.abs(db.POTION_COMPOUND.DRINK_HP))..', Sanity '..(db.POTION_COMPOUND.DRINK_SAN > 0 and '+' or '-')..(math.abs(db.POTION_COMPOUND.DRINK_SAN))..', consumes '..(db.POTION_COMPOUND.DRINK_CONSUME_PERCENT*100)..'% durability, provides '..db.POTION_COMPOUND.DRINK_PERSEC_HP..' Health per 2 seconds for '..db.POTION_COMPOUND.DURATION..' seconds, stacking only duration, not speed, up to '..(db.POTION_COMPOUND.MAX/db.POTION_COMPOUND.DURATION)..' layers ('..db.POTION_COMPOUND.MAX..' seconds). Stacking to max will not increase duration further.\n- Durability: '..(math.floor(1/db.POTION_COMPOUND.DRINK_CONSUME_PERCENT))..' uses, cannot be consumed if durability is below '..(db.POTION_COMPOUND.DRINK_CONSUME_PERCENT*100)..'%.\n- Durability does not break upon depletion.',
        },
        lol_wp_s16_potion_corruption = {
            name = 'Corruption Potion',
            info_instead = '- Type: Special Item/Potion\n- Consumable, non-stackable.\n- \n- Effects upon consumption:\n\tHealth '..(db.POTION_CORRUPTION.DRINK_HP > 0 and '+' or '-')..(math.abs(db.POTION_CORRUPTION.DRINK_HP))..', Sanity '..(db.POTION_CORRUPTION.DRINK_SAN > 0 and '+' or '-')..(math.abs(db.POTION_CORRUPTION.DRINK_SAN))..', consumes '..(db.POTION_CORRUPTION.DRINK_CONSUME_PERCENT*100)..'% durability, provides '..db.POTION_CORRUPTION.DRINK_PERSEC_HP..' Health and '..db.POTION_CORRUPTION.DRINK_PERSEC_SAN..' Sanity per 2 seconds for '..db.POTION_CORRUPTION.DURATION..' seconds, stacking only duration, not speed, up to '..(db.POTION_CORRUPTION.MAX/db.POTION_CORRUPTION.DURATION)..' layers ('..db.POTION_CORRUPTION.MAX..' seconds). Stacking to max will not increase duration further.\n- Passive: [Corruption Touch]\n\tProvides an additional '..db.POTION_CORRUPTION.PLANAR_DMG_WHEN_DRINK..' Planar Damage during the duration, this effect does not stack.\n- Durability: '..(math.floor(1/db.POTION_CORRUPTION.DRINK_CONSUME_PERCENT))..' uses, cannot be consumed if durability is below '..(db.POTION_CORRUPTION.DRINK_CONSUME_PERCENT*100)..'%.\n- Durability does not break upon depletion.',
        },
        lol_wp_s17_luden = {
            name = 'Luden\'s Echo',
            info_instead = '- Type: \n- Planar Damage: '..TUNING.MOD_LOL_WP.LUDEN.PLANAR_DMG..'\n- Attack Range: '..TUNING.MOD_LOL_WP.LUDEN.RANGE..'\n- Sanity: '..(TUNING.MOD_LOL_WP.LUDEN.DARPPERNESS>0 and '+' or '-')..math.abs(TUNING.MOD_LOL_WP.LUDEN.DARPPERNESS)..'\n- Movement Speed +'..((TUNING.MOD_LOL_WP.LUDEN.WALKSPEEDMULT-1)*100)..'%\n- Active: [Arcane Teleport]\n\tRight-click to instantly teleport to the mouse cursor position, consuming '..math.abs(TUNING.MOD_LOL_WP.LUDEN.SKILL_ARCANE_TELE.CONSUME_SAN)..' Sanity and '..TUNING.MOD_LOL_WP.LUDEN.SKILL_ARCANE_TELE.CONSUME..' durability.\n- Passive: [Echo]\n\tAttacks will launch '..TUNING.MOD_LOL_WP.LUDEN.SKILL_ECHO.MISSILE..' magic missiles that bounce once to nearby enemies, dealing '..TUNING.MOD_LOL_WP.LUDEN.SKILL_ECHO.PLANAR_DMG..' Planar Damage, similar to the Bright Bell Staff, with a cooldown of '..TUNING.MOD_LOL_WP.LUDEN.SKILL_ECHO.CD..' seconds.\n- Shadow item, Shadow Level '..TUNING.MOD_LOL_WP.LUDEN.SHADOW_LEVEL..', deals '..((TUNING.MOD_LOL_WP.LUDEN.DMGMULT_TO_PLANAR-1)*100)..'% increased damage to the Moon faction.\n- Durability: '..TUNING.MOD_LOL_WP.LUDEN.FINITEUSES..', does not break when durability is depleted.'
        },
        lol_wp_s17_liandry = {
            name = 'Liandry\'s Torment',
            info_instead = '- Type: Helmet/Mask\n- Defense: '..(TUNING.MOD_LOL_WP.LIANDRY.ABSORB*100)..'%\n- Planar Defense: '..TUNING.MOD_LOL_WP.LIANDRY.DEFEND_PLANAR..'\n- Lightning Resistance: 100%\n- Sanity: '..(TUNING.MOD_LOL_WP.LIANDRY>0 and '+' or '-')..math.abs(TUNING.MOD_LOL_WP.LIANDRY.DARPPERNESS)..'\n- \n- Has goggles effect, immune to sandstorms and moonstorms\n- Immune to sleep effects.\n- Emits a radius 2 white light.\n- Passive: [Torment]\n\tYour attacks will burn enemies, dealing '..(TUNING.MOD_LOL_WP.LIANDRY.SKILL_TORMENT.MAXHP_PERCENT_PLANAR_DMG*100)..'% of their maximum health as Planar Damage every '..TUNING.MOD_LOL_WP.LIANDRY.SKILL_TORMENT.INTERVAL..' seconds, lasting '..TUNING.MOD_LOL_WP.LIANDRY.SKILL_TORMENT.DURATION..' seconds, with a cooldown of '..TUNING.MOD_LOL_WP.LIANDRY.SKILL_TORMENT.CD..' seconds.\n- Passive: [Suffer]\n\tYour attacks deal an additional '..(TUNING.MOD_LOL_WP.LIANDRY.SKILL_SUFFER.PLANAR_DMG*100)..'% Planar Damage based on the damage dealt.\n- Belongs to the Moon faction, deals '..((TUNING.MOD_LOL_WP.LIANDRY.DMGMULT_TO_SHADOW-1)*100)..'% increased damage to the Shadow faction.\n- Durability: None',
        },
        lol_wp_s17_lostchapter = {
            name = 'The Lost Chapter',
            info_instead = '- Type: Amulet/Spellbook\n- Additional Planar Damage: '..TUNING.MOD_LOL_WP.LOSTCHAPTER.PLANAR_DMG_WHEN_EQUIP..'\n- Sanity: '..(TUNING.MOD_LOL_WP.LOSTCHAPTER.DARPPERNESS>0 and '+' or '-')..math.abs(TUNING.MOD_LOL_WP.LOSTCHAPTER.DARPPERNESS)..'\n- Passive: [Enlightenment]\n\tRestores '..(TUNING.MOD_LOL_WP.LOSTCHAPTER.SKILL_ENLIGHTENMENT.RECOVER_SAN_PERCENT*100)..'% Sanity every morning.\n- Passive: [Yumi Appears]\n\tEquipping The Lost Chapter will summon a magical cat pet, Yumi, who will follow the player holding it like Chester, can fly, and will increase Sanity by +20san/min when near the magical cat (requires Gwin mod).\n- Belongs to the Moon faction.\n- Durability: None',
        },
        lol_wp_s18_bloodthirster = {
            name = 'Bloodthirster',
            info_instead = '- Type: Melee Weapon/Bone Sword\n- Attack Damage: '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.DMG..'\n- Critical Chance: '..(TUNING.MOD_LOL_WP.BLOODTHIRSTER.CRITICAL_CHANCE*100)..'% chance to deal '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.CRITICAL_DMGMULT..'x damage\n- Life Steal: '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.DRAIN..'\n- Sanity: '..((TUNING.MOD_LOL_WP.BLOODTHIRSTER.DARPPERNESS > 0 and '+' or '-')..math.abs(TUNING.MOD_LOL_WP.BLOODTHIRSTER.DARPPERNESS))..'\n- Consumes '..math.abs(TUNING.MOD_LOL_WP.BLOODTHIRSTER.ATK_DELTA_SAN)..' Sanity per attack.\n- Passive: [Spiritual Liquid Shield]\n\tGenerates a Tungsten Crown shield on each attack, lasts '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.SKILL_SPIRITUAL_LIQUID_SHIELD.SHIELD_DURATION..' seconds, cooldown '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.SKILL_SPIRITUAL_LIQUID_SHIELD.CD..' seconds.\n- Passive: [Fresh Blood Well]\n\tWhen at full health, overflowed life steal will repair the weapon\'s durability equally.\n- Passive: [Darkspawn Incarnation]\n\tEquipping with Void Hat and Void Robe grants set effect, increasing '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.SUITE_EFFECT.PLANAR_DMG..' Planar Damage.\n- Passive: [Great Devastation]\n\tEquipping with Tyrant Blood Armor and Demon\'s Embrace grants set effect, increasing '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.SUITE_EFFECT_2.DRAIN..' Life Steal and '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.SUITE_EFFECT_2.PLANAR_DMG..' Planar Damage.\n- Shadow Item, Shadow Level '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.SHADOW_LEVEL..', increases '..((TUNING.MOD_LOL_WP.BLOODTHIRSTER.DMGMULT_TO_PLANAR-1)*100)..'% damage to Moon faction.\n- Durability: '..TUNING.MOD_LOL_WP.BLOODTHIRSTER.FINITEUSES..', does not break when durability runs out.',
        },
        lol_wp_s18_stormrazor = {
            name = 'Stormrazor',
            info_instead = '- Type: Melee Weapon/Samurai Sword\n- Attack Damage: '..TUNING.MOD_LOL_WP.STORMRAZOR.DMG..'\n- Critical Chance: '..(TUNING.MOD_LOL_WP.STORMRAZOR.CRITICAL_CHANCE*100)..'% chance to deal '..TUNING.MOD_LOL_WP.STORMRAZOR.CRITICAL_DMGMULT..'x damage\n- Movement Speed: +'..((TUNING.MOD_LOL_WP.STORMRAZOR.WALKSPEEDMULT-1)*100)..'%\n- Active: [Draw Sword]\n\tStormrazor defaults to sheathed, right-clicking the item will draw the sword, cannot attack before drawing, sheathing the sword reduces movement speed by '..((TUNING.MOD_LOL_WP.STORMRAZOR.WALKSPEEDMULT_WITH_SAYA-1)*100)..'% and will automatically repair, repairing '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_SHIV.REPAIR..' durability every '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_SHIV.REPAIR_INTERVAL..' seconds.\n- Active: [Gale Slash]\n\tRight-clicking a target will release a cyclone, dealing '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_WIND_SLASH.DMG..' damage per second, affected by attack multiplier, can destroy rocks and trees, will not destroy buildings, cooldown '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_WIND_SLASH.CD..' seconds.\n- Passive: [Electric Surge]\n\tAttacks deal '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_ELECTRICSLASH.PLANAR_DMG..' Planar Damage and provide '..((TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_ELECTRICSLASH.WALKSPEEDMULT-1)*100)..'% movement speed for '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_ELECTRICSLASH.WALKSPEEDMULT_DURATION..' seconds, cooldown '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_ELECTRICSLASH.CD..' seconds.\n- Passive: [Energy Overflow]\n\tEach attack reduces '..TUNING.MOD_LOL_WP.STORMRAZOR.SKILL_CHARGE.REDUCE_SKILL_ELECTRICSLASH_PER_HIT..' seconds of passive skill cooldown.\n- Drawing the sword plays Zed\'s theme song, sheathing the sword will stop it, can be disabled in mod settings.\n- Moon Faction Item, increases '..((TUNING.MOD_LOL_WP.STORMRAZOR.DMGMULT_TO_SHADOW-1)*100)..'% damage to Shadow faction.\n- Defeating Moose Goose has a '..((TUNING.MOD_LOL_WP.STORMRAZOR.BLUEPRINTDROP_CHANCE.moose*100))..'% chance to drop blueprint.\n- Durability: '..TUNING.MOD_LOL_WP.STORMRAZOR.FINITEUSES..', does not break when durability runs out',
        },
        lol_wp_s18_krakenslayer = {
            name = 'Kraken Slayer',
            info_instead = '- Type: Ranged Weapon/Whale Cannon\n- Attack Damage: '..TUNING.MOD_LOL_WP.KRAKENSLAYER.DMG..'\n- Attack Range: '..TUNING.MOD_LOL_WP.KRAKENSLAYER.RANGE..'\n- Attacks electrify targets, dealing 1.5x damage, 2.5x damage to wet targets.\n- Critical Chance: '..(TUNING.MOD_LOL_WP.KRAKENSLAYER.CRITICAL_CHANCE*100)..'% chance to deal '..TUNING.MOD_LOL_WP.KRAKENSLAYER.CRITICAL_DMGMULT..'x damage\n- Movement Speed: +'..((TUNING.MOD_LOL_WP.KRAKENSLAYER.WALKSPEEDMULT-1)*100)..'%\n- Passive: [Knock It Down]\n\tEvery third attack deals '..TUNING.MOD_LOL_WP.KRAKENSLAYER.SKILL_TAKEDOWN.TRUEDMG..' true damage, affected by attack multiplier, if target loses '..((1-TUNING.MOD_LOL_WP.KRAKENSLAYER.SKILL_TAKEDOWN.GP_PERCENT_LESS_THAN)*100)..'% health, damage increases to '..TUNING.MOD_LOL_WP.KRAKENSLAYER.SKILL_TAKEDOWN.NEW_TRUEDMG..' true damage.\n- Passive: [Whale Hunter]\n\tDeals '..TUNING.MOD_LOL_WP.KRAKENSLAYER.SKILL_KUJIRA.DMGMULT_TO_MOB_ON_WATER..'x damage to aquatic mobs.\n- Defeating Celestial Heroes has a '..(TUNING.MOD_LOL_WP.KRAKENSLAYER.CHANCE_TO_GET_IN_CHEST_AFTER_KILL_BOSS*100)..'% chance to drop in sunken chest.\n- Moon Faction Item, increases '..((TUNING.MOD_LOL_WP.KRAKENSLAYER.DMGMULT_TO_SHADOW-1)*100)..'% damage to Shadow faction.\n- Durability: None',
        },
        lol_wp_s19_archangelstaff = {
            name = 'Archangel\'s Staff',
            info_instead = '- Type: Ranged Weapon/Wand\n- Planar Damage: '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.PLANAR_DMG..'\n- Attack Range: '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.RANGE..'\n- Movement Speed '..((TUNING.MOD_LOL_WP.ARCHANGELSTAFF.WALKSPEEDMULT-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.WALKSPEEDMULT-1)*100)..'%\n- Can inherit passives from stacked Tear of the Goddess when crafted.\n- Passive: [Overload]\n\tReleases a bouncing magic ball from the Light Bulb Wand every '..(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_OVERLOAD.PER_HIT_TIMES-1)..' hits, bouncing 6 times, dealing weapon panel damage.\n- Passive: [Reverence]\n\tGains '..(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_FEAR.PLANAR_DMG_MAXSANPERCENT*100)..'% of maximum sanity as additional planar damage.\n- Passive: [Mana Accumulation]\n\tEach attack stacks '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.COUNT_PER_HIT..' layers of passive, stacking '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.COUNT_PER_HIT_BOSS..' layers if the target is a boss. Each layer provides '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.DARPPERNESS_PER_COUNT..' sanity regeneration, up to '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.MAX_COUNT..' layers, totaling '..(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.DARPPERNESS_PER_COUNT*TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.MAX_COUNT)..' sanity regeneration. Stacking passives has a '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.CD..' second cooldown.\n- When '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_COUNT.MAX_COUNT..' layers are stacked, a fragment of enlightenment can be used to upgrade the item to [Embrace of the Cherub], gaining attribute boosts and special passives.\n- Belongs to the Moon faction, increasing damage to Shadow faction by '..((TUNING.MOD_LOL_WP.ARCHANGELSTAFF.DMGMULT_TO_SHADOW-1)*100)..'%.\n- Durability: None\n- Displays stacked layers below the item.',
        },
        lol_wp_s19_archangelstaff_upgrade = {
            name = 'Seraph\'s Embrace',
            info_instead = '- Type: Ranged Weapon/Wand\n- Planar Damage: '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.PLANAR_DMG..'\n- Attack Range: '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.RANGE..'\n- Sanity: +'..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.DARPPERNESS..'\n- Movement Speed '..((TUNING.MOD_LOL_WP.ARCHANGELSTAFF.WALKSPEEDMULT-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.WALKSPEEDMULT-1)*100)..'%\n- Emits a radius '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.LIGHT.RADIUS..' white light.\n- Passive: [Overload]\n\tReleases a bouncing magic ball from the Light Bulb Wand every '..(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.SKILL_OVERLOAD.PER_HIT_TIMES-1)..' hits, bouncing 6 times, dealing weapon panel damage.\n- Passive: [Reverence]\n\tGains '..((TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.SKILL_FEAR.PLANAR_DMG_MAXSANPERCENT*100))..'% of maximum sanity as additional planar damage.\n- Passive: [Savior\'s Blade]\n\tProvides '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.SKILL_SHIELD.SHIELD_DURATION..' seconds of invincibility shield when taking damage that would reduce your health below '..(TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.SKILL_SHIELD.HP_PERCENT_BELOW*100)..'% of your maximum health, with a '..TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.SKILL_SHIELD.CD..' second cooldown.\n- Belongs to the Moon faction, increasing damage to Shadow faction by '..((TUNING.MOD_LOL_WP.ARCHANGELSTAFF.UPGRADE.DMGMULT_TO_SHADOW-1)*100) ..'%.\n- Durability: None',
        },
        lol_wp_s19_muramana = {
            name = 'Manamune',
            info_instead = '- Type: Melee Weapon/Spear\n- Damage: '..TUNING.MOD_LOL_WP.MURAMANA.DMG..'\n- Attack Range: '..TUNING.MOD_LOL_WP.MURAMANA.RANGE..'\n- Movement Speed '..((TUNING.MOD_LOL_WP.MURAMANA.WALKSPEEDMULT-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.MURAMANA.WALKSPEEDMULT-1)*100)..'%\n- Can inherit passives from stacked Tear of the Goddess when crafted.\n- Passive: [Wind Slash]\n\tReleases a triple hit after every '..(TUNING.MOD_LOL_WP.MURAMANA.SKILL_WINDSLASH.PER_HIT_TIMES-1)..' hits, dealing 3 segments of weapon panel damage.\n- Passive: [Reverence]\n\tGains '..(TUNING.MOD_LOL_WP.MURAMANA.SKILL_FEAR.SAN_PERCENT*100)..'% of maximum sanity as additional physical damage.\n- Passive: [Mana Accumulation]\n\tEach attack stacks '..TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.COUNT_PER_HIT..' layers of passive, stacking '..TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.COUNT_PER_HIT_BOSS..' layers if the target is a boss. Each layer provides '..TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.DARPPERNESS_PER_COUNT..' sanity regeneration, up to '..TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.MAX_COUNT..' layers, totaling '..(TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.DARPPERNESS_PER_COUNT*TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.MAX_COUNT)..' sanity regeneration. Stacking passives has a '..TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.CD..' second cooldown.\n- When '..TUNING.MOD_LOL_WP.MURAMANA.SKILL_COUNT.MAX_COUNT..' layers are stacked, a fragment of enlightenment can be used to upgrade the item to [Sorcerer\'s Edge], gaining attribute boosts and special passives.\n- Belongs to the Moon faction, increasing damage to Shadow faction by '..((TUNING.MOD_LOL_WP.MURAMANA.DMGMULT_TO_SHADOW-1)*100)..'%.\n- Durability: None\n- Displays stacked layers below the item.',
        },
        lol_wp_s19_muramana_upgrade = {
            name = 'Muramana',
            info_instead = '- Type: Melee Weapon/Spear\n- Damage: '..TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.DMG..'\n- Attack Range: '..TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.RANGE..'\n- Sanity: +'..TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.DARPPERNESS..'\n- Movement Speed '..((TUNING.MOD_LOL_WP.MURAMANA.WALKSPEEDMULT-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.MURAMANA.WALKSPEEDMULT-1)*100)..'%\n- Emits a radius '..TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.LIGHT.RADIUS..' white light.\n- Passive: [Wind Slash]\n\tReleases a triple hit after every '..(TUNING.MOD_LOL_WP.MURAMANA.SKILL_WINDSLASH.PER_HIT_TIMES-1)..' hits, dealing 3 segments of weapon panel damage.\n- Passive: [Reverence]\n\tGains '..(TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.SKILL_FEAR.SAN_PERCENT*100)..'% of maximum sanity as additional physical damage.\n- Passive: [Impact]\n\tGains '..(TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.SKILL_SLASH.SAN_PERCENT*100)..'% of maximum sanity as additional planar damage.\n- Belongs to the Moon faction, increasing damage to Shadow faction by '..((TUNING.MOD_LOL_WP.MURAMANA.UPGRADE.DMGMULT_TO_SHADOW-1)*100)..'%.\n- Durability: None',
        },
        lol_wp_s19_fimbulwinter_armor = {
            name = 'Winter\'s Approach',
            info_instead = '- Type: Armor Equipment/Armor\n- Defense: '..(TUNING.MOD_LOL_WP.FIMBULWINTER.ABSORB*100)..'%\n- Warmth: '..TUNING.MOD_LOL_WP.FIMBULWINTER.AVOID_COLD..'\n- Water Resistance: '..(TUNING.MOD_LOL_WP.FIMBULWINTER.WATERPROOF*100)..'%\n- Immune to knockback effects.\n- Movement Speed '..((TUNING.MOD_LOL_WP.FIMBULWINTER.WALKSPEEDMULT-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.FIMBULWINTER.WALKSPEEDMULT-1)*100)..'%\n- Can inherit passives from stacked Tear of the Goddess when crafted.\n- Passive: [Reverence]\n\tGains '..(TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_FEAR.SAN_PERCENT*100)..'% of maximum sanity as planar defense.\n- Passive: [Mana Accumulation]\n\tEach attack stacks '..TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.COUNT_PER_HIT..' layers of passive, stacking '..TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.COUNT_PER_HIT_BOSS..' layers if the target is a boss. Each layer provides '..TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.DARPPERNESS_PER_COUNT..' sanity regeneration, up to '..TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.MAX_COUNT..' layers, totaling '..(TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.MAX_COUNT*TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.DARPPERNESS_PER_COUNT)..' sanity regeneration. Stacking passives has a '..TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.CD..' second cooldown.\n- When '..TUNING.MOD_LOL_WP.FIMBULWINTER.SKILL_COUNT.MAX_COUNT..' layers are stacked, a fragment of enlightenment can be used to upgrade the item to [Apocalypse of Winter], gaining attribute boosts and special passives.\n- Belongs to the Moon faction.\n- Durability: None\n- Displays stacked layers below the item.',
        },
        lol_wp_s19_fimbulwinter_armor_upgrade = {
            name = 'Fimbulwinter',
            info_instead = '- Type: Armor Equipment/Armor\n- Defense: '..(TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.ABSORB*100)..'%\n- Warmth: '..TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.AVOID_COLD..'\n- Water Resistance: '..(TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.WATERPROOF*100)..'%\n- Sanity: +'..TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.DARPPERNESS..'\n- Immune to knockback effects.\n- Immune to freeze effects, immediately unfreezing when frozen.\n- Hunger Speed '..((TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.HUNGER_BURN_RATE-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.HUNGER_BURN_RATE-1)*100)..'%\n- Lightning Resistance: 100%\n- Movement Speed '..((TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.WALKSPEEDMULT-1)>0 and '+' or '-')..(math.abs(TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.WALKSPEEDMULT-1)*100)..'%\n- Emits a radius '..TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.LIGHT.RADIUS..' white light.\n- Passive: [Reverence]\n\tGains '..(TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.SKILL_FEAR.SAN_PERCENT*100)..'% of maximum sanity as planar defense.\n- Passive: [Eternal]\n\tProvides '..TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.SKILL_ENTERNAL.DURANTION..' seconds of invincibility shield when attacking a boss, with a '..TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.SKILL_ENTERNAL.CD..' second cooldown.\n- Passive: [Glacial Amplification]\n\tEquipping with Randuin\'s Omen grants set effects, each attack causing an additional '..(100*(1-TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.SKILL_ICERAISE.SPEEDDOWN))..'% slow and reducing the target\'s damage by '..(100*(1-TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.SKILL_ICERAISE.DOWN_TARGET_ATK))..'% for '..TUNING.MOD_LOL_WP.FIMBULWINTER.UPGRADE.SKILL_ICERAISE.DURATION..' seconds, no cooldown.\n- Belongs to the Moon faction.\n- Durability: None',
        },
    },
    ---@type lol_wp_pedia_iteminfo
    pedia_items_info_key = { -- All entries for pedia items
        name = 'Name: ',
        damage = 'Damage: ',
        walkspeedmult = 'Movement Speed: ',
        dapperness = 'Sanity Impact: ',
        hit_add_hp = 'Attack Health Regeneration: ',
    }
}

local all_repair_tbl_key = { 'REPAIR', 'REPAIR_ARMOR', 'REPAIR_FUELED' }
for id, tbl in pairs(data.pedia_items) do
    for _, v in ipairs(all_repair_tbl_key) do
        local repair = db[v][string.upper(id)]
        if repair then
            local res = ''

            -- Create an array to store key-value pairs
            local sortedArray = {}
            ---@diagnostic disable-next-line: param-type-mismatch
            for key, value in pairs(repair) do
                table.insert(sortedArray, { key = key, value = value })
            end
            -- Sort the array by value in ascending order
            table.sort(sortedArray, function(a, b)
                return a.value < b.value
            end)
            for _, entry in ipairs(sortedArray) do
                res = res .. STRINGS.NAMES[entry.key] .. (entry.value * 100) .. '%/'
            end

            -- ---@diagnostic disable-next-line: empty-block, param-type-mismatch
            -- for prefab, value in pairs(repair) do
            --     res = res .. STRINGS.NAMES[prefab] .. (value * 100) .. '%/'
            -- end
            tbl.info_instead = (tbl.info_instead or '') .. '\n- Repair Materials: ' .. res
            tbl.info_instead = string.sub(tbl.info_instead, 1, -2)
            break
        end
    end
end

return data